export const templates = {
  "7e98ff85-c7be-d251-7f37-73c79ca1942d": {
    json: {
      version: "5.3.0",
      objects: [
        {
          type: "rect",
          version: "5.3.0",
          left: 0,
          top: 0,
          width: 1080,
          height: 1960,
          fill: "transparent",
          id: "workspace",
          selectable: false,
          hasControls: false,
        },
        {
          type: "textbox",
          version: "5.3.0",
          left: 465,
          top: 960,
          width: 154.16,
          height: 22.6,
          fill: "#06c",
          fontFamily: "华康金刚黑",
          fontSize: 20,
          text: "双击输入文123字",
          styles: [],
          minWidth: 20,
          splitByGrapheme: false,
          selectable: true,
          hasControls: true,
        },
      ],
      clipPath: {
        type: "rect",
        version: "5.3.0",
        left: 0,
        top: 0,
        width: 1080,
        height: 1960,
        fill: "transparent",
        id: "workspace",
        selectable: true,
        hasControls: true,
      },
      background: "#fff",
    },
    t: "模板:8fea3626-d47e-5f32-0d48-f645f8706ae3",
  },
  "8b082b88-5bbe-2020-366a-8b12550256cb": {
    json: {
      version: "5.3.0",
      objects: [
        {
          type: "rect",
          version: "5.3.0",
          left: 0,
          top: 0,
          width: 1080,
          height: 1960,
          fill: "transparent",
          id: "workspace",
          selectable: false,
          hasControls: false,
        },
        {
          type: "textbox",
          version: "5.3.0",
          left: 465,
          top: 960,
          width: 154.16,
          height: 22.6,
          fill: "#06c",
          fontFamily: "华康金刚黑",
          fontSize: 20,
          text: "双击输入文123字",
          styles: [],
          minWidth: 20,
          splitByGrapheme: false,
          selectable: true,
          hasControls: true,
        },
      ],
      clipPath: {
        type: "rect",
        version: "5.3.0",
        left: 0,
        top: 0,
        width: 1080,
        height: 1960,
        fill: "transparent",
        id: "workspace",
        selectable: true,
        hasControls: true,
      },
      background: "#fff",
    },
    t: "模板:1d75c74c-fcb4-6ed4-31de-6fc8c48b3a48",
  },
  "269a6480-da45-15aa-7111-cb38d60c0f29": {
    json: {
      version: "5.3.0",
      objects: [
        {
          type: "rect",
          version: "5.3.0",
          left: 0,
          top: 0,
          width: 1080,
          height: 1960,
          fill: "transparent",
          id: "workspace",
          selectable: false,
          hasControls: false,
        },
        {
          type: "textbox",
          version: "5.3.0",
          left: 465,
          top: 960,
          width: 150,
          height: 22.6,
          fill: "#06c",
          fontFamily: "华康金刚黑",
          fontSize: 20,
          text: "双击输入文字",
          styles: [],
          minWidth: 20,
          splitByGrapheme: false,
          selectable: true,
          hasControls: true,
        },
      ],
      clipPath: {
        type: "rect",
        version: "5.3.0",
        left: 0,
        top: 0,
        width: 1080,
        height: 1960,
        fill: "transparent",
        id: "workspace",
        selectable: true,
        hasControls: true,
      },
      background: "#fff",
    },
    t: "模板:e636743b-11f3-dcdb-7604-a33743de7e34",
  },
  "b4c6d373-d31f-6b29-28a2-ec32e6236556": {
    json: {
      version: "5.3.0",
      objects: [
        {
          type: "rect",
          version: "5.3.0",
          left: 0,
          top: 0,
          width: 1080,
          height: 1960,
          fill: "transparent",
          id: "workspace",
          selectable: false,
          hasControls: false,
        },
        {
          type: "textbox",
          version: "5.3.0",
          left: 465,
          top: 960,
          width: 150,
          height: 22.6,
          fill: "#06c",
          fontFamily: "华康金刚黑",
          fontSize: 20,
          text: "双击输入文字",
          styles: [],
          minWidth: 20,
          splitByGrapheme: false,
          selectable: true,
          hasControls: true,
        },
      ],
      clipPath: {
        type: "rect",
        version: "5.3.0",
        left: 0,
        top: 0,
        width: 1080,
        height: 1960,
        fill: "transparent",
        id: "workspace",
        selectable: true,
        hasControls: true,
      },
      background: "#fff",
    },
    t: "模板:eebf863e-6c94-520b-5ecf-cf3ef10f1657",
  },
  "7e964557-c87a-7c8b-3779-b193d169cded": {
    json: {
      version: "5.3.0",
      objects: [
        {
          type: "rect",
          version: "5.3.0",
          left: 0,
          top: 0,
          width: 1080,
          height: 1960,
          fill: "transparent",
          id: "workspace",
          selectable: false,
          hasControls: false,
        },
        {
          type: "textbox",
          version: "5.3.0",
          left: 465,
          top: 960,
          width: 154.16,
          height: 22.6,
          fill: "#06c",
          fontFamily: "华康金刚黑",
          fontSize: 20,
          text: "双击输入文字123",
          styles: [],
          minWidth: 20,
          splitByGrapheme: false,
          selectable: true,
          hasControls: true,
        },
        {
          type: "textbox",
          version: "5.3.0",
          left: 454.92,
          top: 1055.33,
          width: 180,
          height: 22.6,
          fill: "#06c",
          fontFamily: "华康金刚黑",
          fontSize: 20,
          text: "双击输入文啊是的字",
          styles: [],
          minWidth: 20,
          splitByGrapheme: false,
          selectable: true,
          hasControls: true,
        },
      ],
      clipPath: {
        type: "rect",
        version: "5.3.0",
        left: 0,
        top: 0,
        width: 1080,
        height: 1960,
        fill: "transparent",
        id: "workspace",
        selectable: true,
        hasControls: true,
      },
      background: "#F12",
    },
    t: "模板:a28da844-af80-1a41-d5c7-63be7299acb3",
  },
};
